version: '3.5'
services:
    
    rides:
        build:
            context: .
            dockerfile: ride_dockerfile
        image: rides:latest
        ports: 
            - "80:80"
        networks:
            app_net:
                ipv4_address: 173.18.0.3
        volumes: 
            - .:/ride
        environment: 
            - PORT:80
            - TEAM_NAME=CC_0048_0103_0798
networks: 
    app_net:
        ipam: 
            driver: default
            config: 
                - subnet: "173.18.0.0/24"
                      
