version: '3.1'

services:
  zoo:
    image: zookeeper
    restart: on-failure
    hostname: zoo
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181

  rmq:
    image: rabbitmq:3.8.3-management
    ports:
      - 5672:5672
      - 15672:15672

  worker:
    build:
        context: .
        dockerfile: Dockerfile
    command: sh -c "sleep 15 && python worker.py"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - .:/code
    links:
    - rmq
    - zoo
    depends_on:
    - rmq
    - zoo
    restart: on-failure


  orchestrator:
    build:
        context: .
        dockerfile: Dockerfile
    command: sh -c "sleep 30 && python zk_orch.py"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - .:/code
    links:
    - rmq
    - zoo
    depends_on:
    - rmq
    - zoo
    restart: on-failure  
    ports:
      - 5000:5000

