version: '3.1'

services:
  rmq:
    image: rabbitmq:3.8.3-management
    ports:
      - 5672:5672
      - 15672:15672

  master:
    build:
        context: .
        dockerfile: Dockerfile
    command: sh -c "sleep 15 && python master.py"
    volumes:
    - .:/code
    links:
    - rmq
    depends_on:
    - rmq
    restart: on-failure

  slave:
    build:
        context: .
        dockerfile: Dockerfile
    command: sh -c "sleep 15 && python slave.py"
    volumes:
    - .:/code
    links:
    - rmq
    depends_on:
    - rmq
    restart: on-failure

  orchestrator:
    build:
        context: .
        dockerfile: Dockerfile
    command: sh -c "sleep 20 && python zk_orch.py"
    volumes:
        - .:/code
    links:
    - rmq
    depends_on:
    - rmq
    restart: on-failure  
    ports:
      - 5000:5000

